server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      # oneToMany시에 in query 자동 작성
      default_batch_fetch_size: 100
    # db session controller까지 가져오기
    open-in-view: false

logging:
  level:
    '[smash.teams.be]': DEBUG
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기

sentry:
  dsn: https://cc29f1ec6bf3416c89ebd59fcdd28c30@o4505186517057536.ingest.sentry.io/4505186827960320
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0

file:
  path: ./upload/
  location: file:./upload/
  prefix: http://localhost:8080/upload/

JWT_SECRET_KEY: "승민"